name: 'Publish Action'
description: 'An action to publish a blog post'
author: 'Karm Patel'
branding:
  icon: 'upload-cloud'
  color: 'green'

inputs:
  HASHNODE_API_KEY:
    description: 'API key for Hashnode'
    required: true
  HASHNODE_BLOG_ID:
    description: 'Blog ID for Hashnode'
    required: true
  REPO_TOKEN:
    description: 'GitHub repository token'
    required: true
  OPENAI_API_KEY:
    description: 'API key for OpenAI'
    required: true

runs:
  using: 'node16'
  main: 'node index.mjs'





