name: 'Publish Action'
description: 'An action to publish a blog post'
author: 'Karm patel'
branding:
  icon: 'upload-cloud'
  color: 'green'

inputs:
  hashnode-api-key:
    description: 'API key for Hashnode'
    required: true
  hashnode-blog-id:
    description: 'Blog ID for Hashnode'
    required: true
  repo-token:
    description: 'GitHub repository token'
    required: true
  openai-api-key:
    description: 'API key for OpenAI'
    required: true

outputs:
  publish-output:
    description: 'Output for publish blog'

runs:
  using: 'node16'
  main: 'index.mjs'

