name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v4'

      - uses: 'actions/setup-node@v4'
        with:
          node-version: '20.x'

      - name: 'npm build'
        run: 'npm ci && npm run build'
      - id: 'auto-blog-publish-action'
        name: 'auto-blog-publish-action'
        uses: './'
        with:
          HASHNODE_API_KEY: ${{ secrets.HASHNODE_API_KEY }}
          HASHNODE_BLOG_ID: ${{ secrets.HASHNODE_BLOG_ID }}
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
